# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: omnivore-autobuild-test
canonical: https://omnivore.se/test/fhir
name: Omnivore.se test build
status: active
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
license: CC0-1.0
publisher:
  name: Pétur Valdimarsson
  url: https://omnivore.se
dependencies:
  se-baseprofile: dev
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
